### ISSUE TITLE
chromedriver.exe

### ISSUE THREAD

**Issue by leonurium** [s3pt3mb3r/lineatgo#2]
Hi, i am beginner in golang, i try your package and follow intrucstions in readme, i have done create file main.go, and go build this, but when i execute main.exe, i get this error `2018/01/29 22:20:48 Failed to start driver:failed to start service: failed to run command: exec: "chromedriver.exe": executable file not found in %PATH%`, i have done download chrome driver, but i can understand with meaning %PATH% where this is, sorry i am noob

**Comment by vxcall** [comment]
I described how to install chromedriver [HERE](https://github.com/s3pt3mb3r/lineatgo/blob/master/README.md#installation)
I forgot to tell you it. So sorry...
